### ISSUE TITLE
Reynold Request Review: Bean Chart

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/user_charts#1]
See https://github.com/UofS-Pulse-Binfo/user_charts/commit/e7187dc867b549644b1629c6339e76e20d74d189

**Comment by laceysanderson** [comment]
## Code Review:
Comments have been added directly to the commit mentioned above. Summary:
- [ ] Set description on menu item.
- [ ] Don't create your own saveSVGasPNG.js. Instead re-use the existing one by adding it to your page and making sure the chart container stays "chart-svg"
- [ ] Tweak wording/format of the form (see comments).
- [ ] Move Chart options into their own fieldset: `Step #3 Customize Display`
- [ ] See https://github.com/UofS-Pulse-Binfo/user_charts/blob/master/forms/pcoa_scatterplot.form.inc#L161 for an example of how to handle the "Show Example". Please be consistent for maintainability reasons and to ensure the example is treated exactly the same as user entered data for both validation and chart drawing.
- [ ] Don't use javascript to generate your summary table. Instead do this in the drupal form by accessing $form_state['processed'] and using a markup form element (see example below).
- [ ] js/beanplot.chart.js could use more comments. Functions should have a full on docblock like in PHP.

```
$form['summary_table'] = array(
  '#type' => #markup',
  '#markup' => theme('table', array('header' => $header', 'rows' => $rows)),
);
```

**Comment by reynoldtan** [comment]
Not sure of item #3 - Tweak wording/format of the form (see comments).

**Comment by laceysanderson** [comment]
Merged in 👍
